/**
 * modernGraphTool Configuration
 * Generated by Config Editor
 */
const CONFIG = {
  // Phone & Targets to display on initial load.
  INITIAL_PHONES: ["Flo Audio Bluelover"],
  INITIAL_TARGETS: ["∆ Headphones.com IEM DF Target"],
  INITIAL_PANEL: "graph",
  // Default Normalization Type and Value.
  NORMALIZATION: { TYPE: "Hz", HZ_VALUE: 630 },
  // Default Visualization Settings.
  VISUALIZATION: {
    ASPECT_RATIO: "CrinGraph",
    DEFAULT_Y_SCALE: 40,
    LABEL: {
      LOCATION: "BOTTOM_LEFT",
      POSITION: { LEFT: "0", RIGHT: "25", UP: "7", DOWN: "0" },
      TEXT_SIZE: "12px",
      TEXT_WEIGHT: "600",
    },
    BASELINE_LABEL: {
      LOCATION: "TOP_LEFT",
      POSITION: { LEFT: "0", RIGHT: "25", UP: "7", DOWN: "0" },
      TEXT_SIZE: "12px",
      TEXT_WEIGHT: "500",
    },
    RIG_DESCRIPTION: "‎ ",
  },
  // User Interface Settings
  INTERFACE: {
    PREFERRED_DARK_MODE_THEME: "light",
    ALLOW_REMOVING_PHONE_FROM_SELECTOR: true,
	PANEL_POSITION: "right",
    SWITCH_PHONE_PANEL_ON_BRAND_CLICK: true,
    TARGET: {
      ALLOW_MULTIPLE_LINE_PER_TYPE: true,
      OMIT_TARGET_SUFFIX: false,
      COLLAPSE_TARGET_LIST_ON_INITIAL: false,
    },
    HIDE_DEV_DONATE_BUTTON: true,
  },
  // URL Settings
  URL: { AUTO_UPDATE_URL: true, COMPRESS_URL: true },
  // Language Settings
  LANGUAGE: {
    LANGUAGE_LIST: [
      ["en", "English"],
      ["cs", "Čeština"]
    ],
    ENABLE_I18N: true,
    ENABLE_SYSTEM_LANG_DETECTION: true,
  },
  // File Path Settings
  PATH: {
    PHONE_MEASUREMENT: "./data/phones",
    TARGET_MEASUREMENT: "./data/target",
    PHONE_BOOK: "./data/phone_book.json",
  },
  // Watermark Settings
  WATERMARK: [
    {
    TYPE: "TEXT",
    CONTENT: "adam664.github.io", LOCATION: "BOTTOM_RIGHT",
    SIZE: "18px", FONT_FAMILY: "sans-serif", FONT_WEIGHT: "600", COLOR: "#000000", OPACITY: "0.3",
	POSITION: {UP: "6", DOWN: "0", LEFT: "2", RIGHT: "0"},
  },
    {
      TYPE: "IMAGE",
      CONTENT: ["./assets/images/naoegokoro.png"],
      LOCATION: "TOP_RIGHT",
	  POSITION: {UP: "0", DOWN: "5", LEFT: "135", RIGHT: "0"},
      SIZE: "130px",
	  OPACITY: "0.4",
      FONT_FAMILY: "sans-serif",
      FONT_WEIGHT: "600",
    }
  ],
  // Target configuration
  TARGET_MANIFEST: [
    {
      type: "Harman",
      files: ["Harman IE 2019v2", "Harman IE 2017v2"],
    },
    {
      type: "DF",
      files: ["ISO 11904-2 DF Target", "∆ Headphones.com IEM DF Target"],
    }
  ],
  // Multi-Sample Measurement Settings
  MULTI_SAMPLE: { DEFAULT_DISPLAY: "average" },
  // HpTF (Headphone Transfer Function) Sample Deviation Settings
  HPTF: { DEFAULT_DISPLAY: "fill+curves", FILL_OPACITY: 0.3 },
  // Graph Trace Styling
  TRACE_STYLING: {
    PHONE_TRACE_THICKNESS: 2,
    TARGET_TRACE_THICKNESS: 1,
    CURVE_COLOR_PALETTE: [
      "#0072B2",
      "#E69F00",
      "#009E73",
      "#CC79A7",
      "#56B4E9",
      "#D55E00",
      "#F0E442",
      "#000000"
    ],
    CURVE_COLOR_PALETTE_RANDOMIZE: false,
    TARGET_TRACE_DASH: [],
  },
  // Topbar Link List
  TOPBAR: {
    TITLE: { TYPE: "HTML", CONTENT: "<h2>adam's modernGraphTool</h2>" },
    LINK_LIST: [],
  },
  // Preference Bound Settings
  PREFERENCE_BOUND: {
    ENABLE_BOUND_ON_INITIAL_LOAD: true,
    BASE_DF_TARGET_FILE: "∆ Headphones.com IEM DF Target",
    COLOR_FILL: "rgba(180,180,180,0.07)",
    COLOR_BORDER: "rgba(120,120,120,0.5)",
  },
  // Target Customizer Settings
  TARGET_CUSTOMIZER: {
    CUSTOMIZABLE_TARGETS: ["ISO 11904-2 DF Target", "∆ Headphones.com IEM DF Target"],
    FILTERS: [
      { id: "tilt", name: "Tilt", type: "TILT", freq: 0, q: 0 },
      {
        id: "bass",
        name: "Bass",
        type: "LSQ",
        freq: 105,
        q: 0.707,
      },
      {
        id: "treble",
        name: "Treble",
        type: "HSQ",
        freq: 2500,
        q: 0.42,
      },
      { id: "ear", name: "Ear", type: "PK", freq: 2750, q: 1 },
	  { id: "pssr", name: "PSSR", type: "HSQ", freq: 500, q: 0.4 },
    ],
    FILTER_PRESET: [],
    INITIAL_TARGET_FILTERS: [
      {
        name: "ISO 11904-2 DF",
        filter: { tilt: -1 },
      },
      {
        name: "∆ Headphones.com IEM DF Target",
        filter: { tilt: -1 },
      }
    ],
  },
  // Misc Panel Description
  DESCRIPTION: [
    {
      TYPE: "HTML",
    }
  ],
};

window.GRAPHTOOL_CONFIG = CONFIG;